Repository connect-foundation/2019-21, pull requests merged in 2019-12, with the labels that each got.

#262 OAuth login 추가 및 app간 routing
  backend/DB/queries/event.js
  backend/DB/queries/host.js
  backend/express/app.js
  backend/express/auth/passport.js
  backend/express/authentication/google.js
  backend/express/authentication/jwt.js
  backend/express/authentication/token.js
  backend/express/config/express.dev.config.js
  backend/express/routes/auth.js
  frontend/host-app/src/App/App.js
  frontend/main-app/src/components/LoginModal.js
Labels: feature

#294 페이지간 라우팅 구현 및 세션설정
  backend/DB/queries/guest.js
  backend/DB/queries/host.js
  backend/express/app.js
  backend/express/authentication/google.js
  backend/express/authentication/jwt.js
  backend/express/authentication/token.js
  backend/express/config/express.dev.config.js
  backend/express/middleware/authenticate.js
  backend/express/routes/auth.js
  backend/express/utils.js
  backend/graphQL/app.js
  backend/spec/hostDBQuery.test.js
  frontend/main-app/src/components/EventForm.js
Labels: node/express

#309 fix: event table에 eventName 컬럼 추가 및 더미데이터 수정
  backend/DB/dummy/eventDummies.js
  backend/DB/migrations/20191204794363-add-column-event.js
Labels: DB

#311 Hotfix/yarn start script
  backend/socket_io_server/app.js
  package.json
  script/start.sh
  script/start_backend.sh
  script/start_frontend.sh
Labels: hotfix, socket.io, yoga

#312 feature-create event
  backend/DB/queries/event.js
  backend/graphQL/model/hostpage/hostpage.graphql
  backend/graphQL/model/hostpage/hostpage.resolver.js
  frontend/host-app/src/App/App.js
  frontend/host-app/src/components/CreateEventModal/CreateEventModal.js
  frontend/host-app/src/components/CreateEventModal/EndDateField.js
  frontend/host-app/src/components/CreateEventModal/InputStartDate.js
  frontend/host-app/src/components/CreateEventModal/eventModalReducer.js
  frontend/host-app/src/components/HeaderAccountAvata.js
  frontend/host-app/src/libs/gql.js
Labels: feature, graphql, react, yoga

#318 Feature/use questions query hook
  frontend/guest-app/src/apolloHooks/useQueryQuestions.js
  frontend/guest-app/src/libs/useQueryQuestions.js
  frontend/guest-app/src/libs/utils.js
  frontend/host-app/package.json
  frontend/host-app/src/libs/useQueryQuestions.js
  frontend/host-app/src/libs/utils.js
  frontend/libs/useQueryQuestions.js
  frontend/libs/utils.js
Labels: react

#321 create event and setting event
  backend/DB/queries/event.js
  backend/graphQL/model/hostpage/hostpage.graphql
  backend/graphQL/model/hostpage/hostpage.resolver.js
  frontend/host-app/src/components/CreateEventModal/CreateEventModal.js
  frontend/host-app/src/components/EventSettingModal/EventSettingTab/GeneralSetting/GeneralSetting.js
  frontend/host-app/src/components/EventSettingModal/EventSettingTab/GeneralSetting/InputStartDate.js
  frontend/host-app/src/components/EventSettingModal/settingReducer/settingReducer.js
  frontend/host-app/src/libs/gql.js
Labels: feature
