Repository connect-foundation/2019-21, pull requests merged in 2019-11, with the labels that each got.

#81 env: 수동 배포 설정 추가
  backend/.env
  backend/.gitignore
  backend/docker/docker-product.yml
  backend/docker/dockerfiles/.dockerignore
  backend/docker/dockerfiles/node.Dockerfile
  backend/express/app.js
  backend/package.json
  backend/script/build-docker-image.sh
  backend/yarn.lock
Labels: CI/CD, ENV, priority:high

#88 Main app
  frontend/main-app/package.json
  frontend/main-app/src/App.css
  frontend/main-app/src/App.js
  frontend/main-app/src/compounds/EventForm.js
  frontend/main-app/src/compounds/Header.js
  frontend/main-app/src/compounds/HostLogin.js
  frontend/main-app/src/index.css
  frontend/main-app/yarn.lock
Labels: feature, html&css, priority:high, react

#90 env: add DB TEST 형식 코드 추가#53
  backend/package-lock.json
  backend/package.json
  backend/spec/dbtest.db.spec.js
Labels: DB, ENV

#83 docs: add 클라우드 서버 기본 및 클라우드 세팅 문서
  docs/클라우드 서버 기본 및 배포 설정.md
Labels: CI/CD, bug, docs, priority:low

#95 Env docker db setting
  backend/.env
  backend/.env.example
  backend/.gitignore
  backend/DB/sequelize.config.js
  backend/DB/utils.js
  backend/docker/docker-development.yml
  backend/docker/docker-product.yml
  backend/docker/dockerfiles/node.Dockerfile
  backend/package.json
  backend/spec/app.test.js
  backend/yarn.lock
Labels: CI/CD, DB, ENV

#100 Env/auto build and deploy setting
  .gitignore
  backend/.env.example
  backend/.eslintignore
  backend/.gitignore
  package.json
  script/build_backend.sh
  script/build_front.sh
  script/deploy.sh
  script/deploy_demon.sh
  script/deploy_undo.sh
Labels: CI/CD, ENV

#99 Main app
  frontend/main-app/public/google.png
  frontend/main-app/public/googlePressed.png
  frontend/main-app/public/naver.png
  frontend/main-app/src/App.js
  frontend/main-app/src/compounds/EventForm.js
  frontend/main-app/src/compounds/Header.js
  frontend/main-app/src/compounds/HostLogin.js
  frontend/main-app/src/compounds/HostLoginMessage.js
  frontend/main-app/src/compounds/LoginModal.js
Labels: priority:high, react

#92 fix: 테스트 코드 실행하는 script 에러 수정 #91 #102
  backend/spec/dbtest.db.spec.js
Labels: DB, bug

#103 DB - 스키마 설계 재정의 및 migration,seeder 수정, api 추가 #96
  backend/DB/migrations/20191114022801-create-like.js
  backend/DB/migrations/20191114085344-add-association-like.js
  backend/DB/models/guest.js
  backend/DB/models/like.js
  backend/DB/models/question.js
  backend/DB/queries/event.js
  backend/DB/utils.js
  backend/express/app.js
Labels: API, DB, node/express

#101 Feature/express serve react apps
  backend/.eslintignore
  backend/.prettierrc
  backend/express/app.js
  frontend/guest-app/config/paths.js
  frontend/host-app/config/paths.js
  frontend/main-app/config/paths.js
Labels: node/express, react

#111 doc: 2주차 발표자료 업로드
  docs/발표자료/2주차/api-test.png
  docs/발표자료/2주차/entity.png
  docs/발표자료/2주차/host-app.png
  docs/발표자료/2주차/main-app.png
  docs/발표자료/2주차/sequelize.png
  docs/발표자료/2주차/발표자료(2주차) copy.md
  docs/발표자료/2주차/발표자료(2주차).md
Labels: docs

#133 Feature: guest app 네비바, 탭바, 질문 탭 일부 구현
  frontend/guest-app/package.json
  frontend/guest-app/src/App.js
  frontend/guest-app/src/App/App.css
  frontend/guest-app/src/App/App.js
  frontend/guest-app/src/App/App.test.js
  frontend/guest-app/src/QuestionCard.js
  frontend/guest-app/src/QuestionContainer.js
  frontend/guest-app/src/components/NavBar/LeftNavMenuBar.js
  frontend/guest-app/src/components/NavBar/NavBar.js
  frontend/guest-app/src/components/Question/LikeButton.js
  frontend/guest-app/src/components/Question/QuestionCard.js
  frontend/guest-app/src/components/Question/QuestionContainer.js
  frontend/guest-app/src/components/Question/QuestionDummyData.js
  frontend/guest-app/src/components/Question/UndoLikeModal.js
  frontend/guest-app/src/components/Question/UserAvata.js
  frontend/guest-app/src/components/Tab/TabBar.js
  frontend/guest-app/src/components/Tab/TabIcons.js
  frontend/guest-app/src/components/Tab/TabPanel.js
  frontend/guest-app/src/index.js
  frontend/guest-app/yarn.lock
Labels: priority:high, react

#136 host page - 이벤트 만들기 모달 #62
  .gitignore
  backend/spec/dbtest.db.spec.js
  frontend/host-app/package.json
  frontend/host-app/src/App.js
  frontend/host-app/src/components/Column.js
  frontend/host-app/src/components/Content.js
  frontend/host-app/src/components/CreateEventModal/ButtonField.js
  frontend/host-app/src/components/CreateEventModal/CreateEventModal.js
  frontend/host-app/src/components/CreateEventModal/EndDateField.js
  frontend/host-app/src/components/CreateEventModal/HashTagsField.js
  frontend/host-app/src/components/CreateEventModal/InputEventName.js
  frontend/host-app/src/components/CreateEventModal/InputHashTag.js
  frontend/host-app/src/components/CreateEventModal/InputStartDate.js
  frontend/host-app/src/components/CreateEventModal/eventModalReducer.js
  frontend/host-app/src/components/Header.js
  frontend/host-app/src/components/Nav.js
  frontend/host-app/src/components/Title.js
  frontend/host-app/yarn.lock
  frontend/main-app/src/App.js
  frontend/main-app/src/components/EventForm.js
  frontend/main-app/src/components/Header.js
  frontend/main-app/src/components/HostLoginMessage.js
  frontend/main-app/src/components/LoginModal.js
Labels: feature, react

#145 feat(guest-app): 실시간 투표 tab
  frontend/guest-app/package.json
  frontend/guest-app/src/App/App.js
  frontend/guest-app/src/components/Poll/Item.js
  frontend/guest-app/src/components/Poll/PollCard.js
  frontend/guest-app/src/components/Poll/PollContainer.js
  frontend/guest-app/src/components/Poll/PollDummyData.js
  frontend/guest-app/src/components/Poll/RatingBlock.js
  frontend/guest-app/src/components/Poll/SelectionItems.js
  frontend/guest-app/yarn.lock
  frontend/host-app/src/components/Poll/DateItems.js
  frontend/host-app/src/components/Poll/Duplication.js
  frontend/host-app/src/components/Poll/MultipleItems.js
  frontend/host-app/src/components/Poll/NewPollModal.js
  frontend/host-app/src/components/Poll/PollName.js
  frontend/host-app/src/components/Poll/RatingBlock.js
  frontend/host-app/src/components/Poll/TextItems.js
Labels: feature, priority:middle, react

#156 fix: host app 투표만들기 버튼이 없어서 투표만들기 모달창을 못띄우는 문제 해결
  frontend/host-app/src/components/HeaderConfigAvata.js
  frontend/host-app/src/components/Poll/NewPollModal.js
  frontend/host-app/src/components/Questions/QuestionContainer.js
Labels: bug

#162 env: eslint error 발생시에도 dev server가 실행되도록 webpack 설정 수정
  frontend/guest-app/config/webpack.config.js
  frontend/host-app/config/webpack.config.js
  frontend/main-app/config/webpack.config.js
Labels: enhancement

#158 Guest 실시간 투표 상태관리 기능
  frontend/guest-app/src/components/Poll/ActiveRating.js
  frontend/guest-app/src/components/Poll/Item.js
  frontend/guest-app/src/components/Poll/PollCard.js
  frontend/guest-app/src/components/Poll/PollContainer.js
  frontend/guest-app/src/components/Poll/PollDummyData.js
  frontend/guest-app/src/components/Poll/RatingItem.js
  frontend/guest-app/src/components/Poll/SelectionItems.js
  frontend/host-app/src/components/HeaderConfigAvata.js
  frontend/host-app/src/components/Poll/NewPollModal.js
  frontend/host-app/src/components/Questions/QuestionContainer.js
Labels: feature, priority:middle

#159 guest-app Emoji 기능 구현
  frontend/guest-app/src/components/Emoji/EmojiArea.js
  frontend/guest-app/src/components/Emoji/EmojiPickerModal.js
  frontend/guest-app/src/components/Question/QuestionCard.js
  frontend/host-app/src/components/HeaderConfigAvata.js
  frontend/host-app/src/components/Poll/NewPollModal.js
  frontend/host-app/src/components/Questions/QuestionContainer.js
  package.json
  yarn.lock
Labels: feature, react

#215 fix: fix ignore babel build ignore directorys
  backend/script/build.sh
Labels: ENV

#237 실시간 질문 데이터베이스 저장 #170
  backend/DB/queries/guest.js
  backend/DB/queries/question.js
  backend/package.json
  backend/socket_io_server/socketHandler/Question/questionCreate.socketHandler.js
  frontend/guest-app/src/components/Question/QuestionContainer.js
  package.json
  yarn.lock
Labels: API, DB, socket.io
